version : '3.3'
services:
  db:
    image: mysql
    container_name: "db"
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    ports :
      - 3306:3306
    environment :
       MYSQL_USER: user
       MYSQL_ROOT_PASSWORD: 123123
       MYSQL_PASSWORD: 123123
       MYSQL_DATABASE : meetingroomservice
  monitor:
    image: adminer
    container_name: "monitor"
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  web:
    build: ./meetingroomservice
    container_name: "web"
    restart: always
    command: bash -c "./wait-for-it.sh db:3306 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db